"""postgresql_schema_refinements

Revision ID: 523e1d97deda
Revises: 0006
Create Date: 2026-08-31 15:51:53.569510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '523e1d97deda'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.add_column('interview_evaluations', sa.Column('evaluation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('recruiter_profiles', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'recruiter_profiles', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recruiter_profiles', type_='foreignkey')
    op.drop_column('recruiter_profiles', 'company_id')
    op.drop_column('interview_evaluations', 'evaluation_json')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_column('audit_logs', 'meta_data')
    # ### end Alembic commands ###
