"""add_company_fields

Revision ID: cc283912283e
Revises: 523e1d97deda
Create Date: 2026-08-31 15:53:09.146871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc283912283e'
down_revision: Union[str, None] = '523e1d97deda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('industry', sa.String(length=150), nullable=True))
    op.add_column('companies', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('company_size', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'logo_url')
    op.drop_column('companies', 'location')
    op.drop_column('companies', 'company_size')
    op.drop_column('companies', 'description')
    op.drop_column('companies', 'industry')
    # ### end Alembic commands ###
